#!/usr/bin/env bash
# OpenCode generator
#
# Produces TypeScript plugin wrappers for the OpenCode platform.
# These plugins implement the same hook logic as the Claude Code bash hooks,
# but using OpenCode's event-based TypeScript plugin system.
#
# Output files (written under ${PROJECT_DIR}/${agent_dir}/hooks/):
#   validate-on-write.ts   — fires on tool.execute.after for write/edit events;
#                            shells out to the bash validators in hooks/validators/
#   audit-docs-plugin.ts   — fires on tool.execute.after for git commit bash calls;
#                            shells out to audit-docs-hook.sh (advisory, never blocks)
#
# Assumptions about OpenCode plugin format (as of framework authoring, 2025):
#   - Plugins are ES modules with a default export object.
#   - The exported object has: event (string), filter (function), handler (async function).
#   - event:   the OpenCode event name, e.g. "tool.execute.after"
#   - filter:  receives an event object; return true to run the handler.
#   - handler: receives the same event object; throw to block the operation.
#   - event.tool: lowercase tool name ("write", "edit", "bash", etc.)
#   - event.args: the tool's arguments object (e.g. { file_path: "...", command: "..." })
#   - Plugins are auto-discovered from the agent_dir/hooks/ directory; no registration needed.
#   - execSync from Node's "child_process" is available (plugins run in Node.js).
#   - __dirname resolves to the hooks/ directory at runtime.
#
# Sourced by generate.sh; do not run directly.

generate_opencode_plugins() {
  local agent_dir
  agent_dir="$(jq_read '.agent_dir')"

  local post_tool_use_hooks audit_docs
  post_tool_use_hooks="$(jq_read '.features.post_tool_use_hooks')"
  audit_docs="$(jq_read '.features.audit_docs')"

  # validate-on-write.ts is only useful when post_tool_use_hooks is enabled
  if [[ "$post_tool_use_hooks" == "true" ]]; then
    generate_validate_on_write_ts "$agent_dir"
  fi

  # audit-docs-plugin.ts is only useful when the audit_docs feature is enabled
  if [[ "$audit_docs" == "true" ]]; then
    generate_audit_docs_plugin_ts "$agent_dir"
  fi
}

generate_validate_on_write_ts() {
  local agent_dir="$1"

  # Build the VALIDATORS array entries.
  # Guard against null or missing linters/type_checkers arrays using // [].
  local validators_lines=""
  local linter_count type_checker_count
  linter_count="$(jq '(.linters // []) | length' <<< "$DISCOVERY_JSON")"
  type_checker_count="$(jq '(.type_checkers // []) | length' <<< "$DISCOVERY_JSON")"

  for (( i=0; i<linter_count; i++ )); do
    local name
    name="$(lowercase_name "$(jq_read ".linters[$i].name")")"
    # Skip entries with a missing or empty name field
    [[ -z "$name" ]] && continue
    validators_lines+="  \"${name}_validator.sh\","$'\n'
  done
  for (( i=0; i<type_checker_count; i++ )); do
    local name
    name="$(lowercase_name "$(jq_read ".type_checkers[$i].name")")"
    # Skip entries with a missing or empty name field
    [[ -z "$name" ]] && continue
    validators_lines+="  \"${name}_validator.sh\","$'\n'
  done

  # Build the file content by concatenating three parts:
  #   1. The static header (up to and including the VALIDATORS array opening bracket)
  #   2. The dynamic validators list (built above from discovery JSON)
  #   3. The static footer (closing bracket and the rest of the plugin body)
  #
  # Quoted heredocs (<<'TS') for the static parts mean bash passes the body through
  # completely literally — $ and ` are untouched. The dynamic part (validators_lines)
  # contains only double-quoted strings and no backticks, so it is safe to interpolate.

  local header footer
  # shellcheck disable=SC2016  # single-quoted heredoc — $ intentionally unexpanded
  header="$(cat <<'TS'
// validate-on-write.ts — PostToolUse validator for OpenCode
// Shells out to the same bash validators used by Claude Code.
// This file is auto-generated by framework/generator/generators/opencode.sh.
import { execSync } from "child_process";
import { resolve } from "path";

const HOOKS_DIR = resolve(__dirname, "validators");

// One entry per linter/type-checker detected during project discovery.
// To add or remove validators, re-run the generator or edit this array manually.
const VALIDATORS = [
TS
)"

  # shellcheck disable=SC2016  # single-quoted heredoc — $ intentionally unexpanded
  footer="$(cat <<'TS'
];

export default {
  event: "tool.execute.after",
  filter: (event: any) => ["write", "edit"].includes(event.tool),
  handler: async (event: any) => {
    const input = JSON.stringify({ tool_input: event.args });
    for (const validator of VALIDATORS) {
      let output = "";
      try {
        output = execSync(`bash "${HOOKS_DIR}/${validator}"`, {
          input,
          encoding: "utf-8",
          timeout: 120_000,
        });
      } catch (err: any) {
        // execSync throws on non-zero exit; capture stdout so we can still
        // parse the validator's JSON decision even when the script exits 1.
        output = err.stdout || "";
      }
      // Parse JSON output — validators communicate decisions via stdout.
      let blockError: Error | null = null;
      try {
        const result = JSON.parse(output || "{}");
        if (result.decision === "block") {
          blockError = new Error(result.reason ?? "Validator blocked the operation (no reason given)");
        }
      } catch {
        // Non-JSON or empty output — allow and continue.
      }
      if (blockError) throw blockError;
    }
  },
};
TS
)"

  local content="${header}"$'\n'"${validators_lines}${footer}"
  write_file "${PROJECT_DIR}/${agent_dir}/hooks/validate-on-write.ts" "$content"
}

generate_audit_docs_plugin_ts() {
  local agent_dir="$1"

  # Use a quoted heredoc so bash does not expand $ or ` inside the TypeScript body.
  # shellcheck disable=SC2016  # single-quoted heredoc — $ intentionally unexpanded
  local content
  content="$(cat <<'TS'
// audit-docs-plugin.ts — Post-commit doc staleness warning for OpenCode
// This file is auto-generated by framework/generator/generators/opencode.sh.
import { execSync } from "child_process";
import { resolve } from "path";

const HOOK_SCRIPT = resolve(__dirname, "audit-docs-hook.sh");

export default {
  event: "tool.execute.after",
  filter: (event: any) =>
    event.tool === "bash" && (event.args?.command || "").includes("git commit"),
  handler: async (event: any) => {
    const input = JSON.stringify({ tool_input: event.args });
    let output = "";
    try {
      output = execSync(`bash "${HOOK_SCRIPT}"`, {
        input,
        encoding: "utf-8",
        timeout: 10_000,
      });
    } catch (err: any) {
      // audit-docs-hook.sh is advisory — if the script errors out, swallow and continue.
      output = err.stdout || "";
    }
    // Only warn; never throw — this plugin must never block a git commit.
    try {
      const result = JSON.parse(output || "{}");
      if (result.reason) {
        console.warn("[audit-docs]", result.reason);
      }
    } catch {
      // Non-JSON output from the hook script — ignore silently.
    }
  },
};
TS
)"

  write_file "${PROJECT_DIR}/${agent_dir}/hooks/audit-docs-plugin.ts" "$content"
}
